#######################################################
### User settings should be specified in that block ###

#---- Directory with sample files (.fasta) ----
samples_dir: "data_input/samples" # directory with all samples in .fasta format

#---- Species ----
reference: "cerevisiae" # fasta-file name reference species without extension
species: "saccharomyces" # group of species for RepeatMasker. The species name must be a valid NCBI Taxonomy Database species name and be contained in the RepeatMasker repeat database (for example, "carnivora")

#---- Whitelist settings ----
boundary: 1000000 # min boundary for scaffold length

#---- Plot settings ----
filter_range: 1 # min length boundary for common sequence in .tab, for mammals recommended 5000
plot_original: true # if true plot also based on unfiltered (original) .tab

###              End of user settings               ###
#######################################################



#---- Dirs ----
whitelists_dir: "data_input/whitelists"
reports_dir: "data_input/reports"

samples_splitted_dir: "data_output/splitted"

out_trf_dir: "data_output/trf"
out_wm_dir: "data_output/windowmasker"
out_rm_dir: "data_output/repeatmasker"

out_gff_trf_dir: "data_output/gff/trf"
out_gff_wm_dir: "data_output/gff/windowmasker"
out_gff_rm_dir: "data_output/gff/repeatmasker"
out_gff_merged_dir: "data_output/gff/merged"
out_bedtools_dir: "data_output/bedtools"
out_lastdbal_dir: "data_output/lastdbal"
out_mavr_dir: "data_output/mavr"

scripts_dir: "workflow/scripts"

log_dir: "logs"
cluster_log_dir: "cluster_logs"

conda_config: "workflow/envs/conda.yaml"

#---- Threads ----
split_fasta_threads: 1
trf_threads: 1
trf_gff_threads: 1
merge_gff_threads: 1
repeatmasker_threads: 24
wm_counts_threads: 8
wm_windowmasker_threads: 8
wm_gff_threads: 1
bedtools_sort_threads: 8
bedtools_threads: 8
lastdb_threads: 16
lastal_threads: 16
last_tar_threads: 4
plot_last_tab_threads: 1

#---- Time ----
split_fasta_time: "00:30:00"
trf_time: "07:00:00"
trf_gff_time: "00:30:00"
merge_gff_time: "00:30:00"
repeatmasker_time: "72:00:00"
wm_counts_time: "04:00:00"
wm_windowmasker_time: "04:00:00"
wm_gff_time: "00:10:00"
bedtools_sort_time: "01:00:00"
bedtools_time: "01:00:00"
lastdb_time: "10:00:00"
lastal_time: "10:00:00"
last_tar_time: "00:30:00"
plot_last_tab_time: "02:00:00"

#---- Memory ----
split_fasta_mem_mb: 10000
trf_mem_mb: 50000
trf_gff_mem_mb: 10000
merge_gff_mem_mb: 10000
repeatmasker_mem_mb: 100000
wm_counts_mem_mb: 10000
wm_windowmasker_mem_mb: 10000
wm_gff_mem_mb: 3000
bedtools_sort_mem_mb: 20000
bedtools_mem_mb: 20000
lastdb_mem_mb: 50000
lastal_mem_mb: 200000
last_tar_mem_mb: 3000
plot_last_tab_mem_mb: 50000


